# Generated by Django 5.0 on 2024-04-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0025_employeeloanrepaymenthistory'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=220, null=True)),
                ('customer_bill_address', models.CharField(max_length=255)),
                ('customer_gst_treatment', models.CharField(max_length=255)),
                ('customer_gst_number', models.CharField(max_length=255)),
                ('customer_place_of_supply', models.CharField(max_length=255)),
                ('estimate_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('reference_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('terms_and_condition', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='')),
                ('sub_total', models.FloatField()),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('tax_amount_igst', models.FloatField()),
                ('shipping_charge', models.FloatField()),
                ('adjustment', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('converted_to_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.invoice')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.paymentterms')),
            ],
        ),
    ]
