# Generated by Django 5.0 on 2024-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0026_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='estimate_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
