# Generated by Django 5.0 on 2024-04-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0027_estimate_estimate_number'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='payment_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.company_payment_term'),
        ),
    ]
