# Generated by Django 5.0 on 2024-04-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0028_alter_estimate_payment_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='converted_to_invoice',
        ),
    ]
