# Generated by Django 5.0 on 2024-04-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0029_remove_estimate_converted_to_invoice'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('tax_rate', models.FloatField()),
                ('discount', models.FloatField()),
                ('total', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.estimate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.items')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
