# Generated by Django 5.0 on 2024-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0035_rename_tax_amount_igst_saleorder_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved')], max_length=255),
        ),
    ]
